-- STEP 1. CHANGE DATABASE
USE INDIA_GTSG;

-- STEP 2. DROP TABLES
DROP TABLE RFT_P6;
DROP TABLE SHEET1$;

-- STEP 3. IMPORT EXCEL FILE (RFT DATA)
-- STEP 4. RUN EXE FILE.


-- TO VIEW TABLES
SELECT * FROM RFT_P6;
SELECT * FROM UT;
